### ISSUE TITLE
Add tests for tag URIs

### ISSUE THREAD

**Issue by Julian** [python-jsonschema/referencing-suite#9]
We have tests for HTTP(s) and URN schemed URIs.

It probably couldn't hurt to have some for the [tag scheme](https://en.wikipedia.org/wiki/Tag_URI_scheme).

At least one example is [here](https://github.com/python-jsonschema/jsonschema/issues/1012#issue-1427096702).

**Comment by joooeey** [comment]
I think the focus on the tag scheme is a bit odd. Of the over 300 URI  schemes registered with IANA, tag is not the third-most important. But it's a great example for a semi-exotic URI/scheme, especially because we have the linked test case (low hanging fruit).
What about `file`, `ftp`, etc.? Does it make sense to add tests for those too?

**Comment by Julian** [comment]
Those schemes are basically similar in syntax to other ones (well, HTTP), and they're also "old", so it's unlikely an implementation that works for one will fail on another. Tag is both newer and also "different" even from URN because of the commas, so it seemed more likely that some language will not necessarily have good `tag` URI support in its standard library.

Meanwhile I don't expect any to have issue with any of the above "in reality", but I'm ok with adding tests for any or all if you're interested!

**Comment by joooeey** [comment]
I think `tag` is a good one to throw into the tests because it's perfectly valid in the spec and new. Virtually nobody uses it, (especially not in jsonschema), so it might trip up many implementers which is exactly what's intended.

I do think `file` scheme should absolutely be in there because there are applications that act like there's only the web and others that act like there's only the file system.

I just looked through the examples and noticed that very common and meaningful elements of many URI schemes (e.g. https) such as `?` and `#` are not in there.

**Comment by Julian** [comment]
> I do think file scheme should absolutely be in there because there are applications that act like there's only the web and others that act like there's only the file system.

PR definitely welcome! #8 is essentially the existing issue for `file://`.

> very common and meaningful elements of many URI schemes (e.g. https) such as ? and # are not in there.

Empty fragments are definitely there, see e.g. absolute-uri-empty-fragment.json -- Non-empty fragments aren't valid in IDs (IIRC in any version but I forget). I *think* query strings aren't either, but I also forget. If you do check and find them valid, PR certainly welcome there too (or else an issue).
